version: '3.7'
services:
    # imagem micro 02
    app:
        build:
            args:
                user: ${DOCKER_USER}
                uid: ${DOCKER_UID}
            context: ./
            dockerfile: Dockerfile
        restart: unless-stopped
        volumes:
            - ./:/var/www
        networks:
            - microservices_02

    # imagem nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - 8001:80
            #- 443:443
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - microservices_02

    # imagem banco de dados
    db:
        image: mysql:5.7.22
        restart: unless-stopped
        ports:
            - '3307:3306'
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - ./.docker/mysql/data:/var/lib/mysql
        networks:
            - microservices_02

    # imagem phpmyadmin
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: unless-stopped
        ports:
            - 8086:80
        environment:
            PMA_ARBITRARY: 1
            PMA_HOST: db
            PMA_USER: ${DB_USERNAME}
            PMA_PASSWORD: ${DB_PASSWORD}
        links:
            - db
        networks:
            - microservices_02

    # redis
    redis:
        image: redis:latest
        ports:
            - 6379:6379
        networks:
            - microservices_02

    # queue
    queue:
        build:
            args:
                user: ${DOCKER_USER}
                uid: ${DOCKER_UID}
            context: ./
            dockerfile: Dockerfile
        command: 'php artisan queue:work'
        restart: unless-stopped
        volumes:
            - ./:/var/www
        depends_on:
            - redis
        networks:
            - microservices_02

networks:
    microservices_02:
        driver: bridge
